#!/usr/bin/env python3
"""
Add FAQ structured data to the equipment reference pages.

Why this exists
---------------
App Store ranking runs on downloads and keywords. AI assistants recommending an
app run on web representation: whether a question a technician actually asks is
answered in plain text somewhere crawlable. In 2026 roughly one in ten people
first heard about the app they installed from an assistant, level with Google.

These pages already answer those questions for humans. This makes the same
answers machine readable, without changing a single visible pixel, by emitting
schema.org FAQPage JSON LD built from the entries already on the page.

Safe to run repeatedly. Any block written by a previous run is replaced.

    python3 scripts/build_reference_faq.py          # write
    python3 scripts/build_reference_faq.py --check  # report only, change nothing
"""

import glob
import html as htmllib
import json
import re
import sys

MARK_OPEN = "<!-- reference-faq:begin (generated by scripts/build_reference_faq.py) -->"
MARK_CLOSE = "<!-- reference-faq:end -->"

# Trailing words on an h1 that describe the document, not the equipment.
TAIL = re.compile(
    r"\s+(fault and status codes|status and fault codes|error codes|fault codes"
    r"|alarms and faults|alarms|codes|reference|field reference)\s*$",
    re.I,
)

MAX_ANSWER = 1200


def text_of(fragment: str) -> str:
    """Visible text from a fragment of markup."""
    s = re.sub(r"<br\s*/?>", " ", fragment)
    s = re.sub(r"<[^>]+>", "", s)
    s = htmllib.unescape(s)
    return re.sub(r"\s+", " ", s).strip()


# Which trade each app serves. Used to phrase questions on topic pages, where
# there is no single piece of equipment to name.
DOMAIN = {
    "droptubebuilder": "fuel systems",
    "loopwatt": "fire alarm systems",
    "plugwatt": "EV charging",
    "rackwatt": "data center operations",
    "storewatt": "battery energy storage",
    "fieldwatt": "solar PV",
}


def subject_of(path: str, page: str):
    """Returns (kind, name).

    Two page shapes exist and they need different questions. An equipment page
    names a model and ends with a document phrase such as "Fault and Status
    Codes"; stripping that phrase leaves the equipment. A topic page does not,
    and asking "what does X mean on a Bms Faults" would be nonsense, so those
    are phrased against the trade instead.
    """
    m = re.search(r"<h1[^>]*>(.*?)</h1>", page, re.S)
    if not m:
        return None, None
    raw = text_of(m.group(1))
    if TAIL.search(raw):
        name = TAIL.sub("", raw).strip()
        if name:
            return "equipment", name
    app = path.split("/")[0]
    return "topic", DOMAIN.get(app, "the field")


def entries(page: str):
    """Each reference entry as (heading, answer)."""
    for m in re.finditer(r'<div class="refEntry"[^>]*>(.*?)</div>\s*(?=<div class="refEntry"|<div class="refSiblings"|<div class="refCross"|</section>|<footer)', page, re.S):
        block = m.group(1)
        h = re.search(r"<h2[^>]*>(.*?)</h2>", block, re.S)
        if not h:
            continue
        heading = text_of(re.sub(r'<a class="refPermalink".*?</a>', "", h.group(1), flags=re.S))
        if not heading:
            continue

        parts = []
        for seg in re.finditer(r'<div class="refLabel">(.*?)</div>|<p[^>]*>(.*?)</p>', block, re.S):
            label, para = seg.group(1), seg.group(2)
            if label is not None:
                parts.append(text_of(label).rstrip(":") + ":")
            elif para is not None:
                t = text_of(para)
                if t:
                    parts.append(t)
        answer = " ".join(parts).strip()
        if len(answer) > MAX_ANSWER:
            answer = answer[:MAX_ANSWER].rsplit(" ", 1)[0] + "…"
        if answer:
            yield heading, answer


def article_for(word: str) -> str:
    """a or an, by sound rather than spelling for the letters that matter here.

    Model names are read letter by letter, so "FE Petro" takes "an" because F
    is pronounced "eff". Spelling alone would get this wrong."""
    if not word:
        return "a"
    first = word[0].upper()
    rest = word[1:2]
    # An initialism: consecutive capitals, or a single letter before a space.
    looks_initialism = first.isalpha() and (rest.isupper() or rest in ("", " ", "-"))
    if looks_initialism and first in "AEFHILMNORSX":
        return "an"
    return "an" if first in "AEIOU" else "a"


def question_for(heading: str, kind: str, name: str) -> str:
    # Some entries are already phrased as questions. Leave those alone.
    if heading.rstrip().endswith("?"):
        return heading.rstrip()
    low = heading.lower()
    # "can" is deliberately absent: CAN is a bus name in these trades and
    # "CAN bus is the primary diagnostic path" is not a question.
    if low.startswith(("how ", "what ", "when ", "why ", "where ", "which ", "does ")):
        return heading if heading.endswith("?") else heading + "?"
    if low in ("overview", "about", "summary", "scope"):
        return f"What is the {name}?" if kind == "equipment" else f"What does this cover in {name}?"
    if kind == "equipment":
        return f"What does {heading} mean on {article_for(name)} {name}?"
    return f"What does {heading} mean in {name}?"


def build(page: str, kind: str, name: str) -> str | None:
    faqs = [
        {
            "@type": "Question",
            "name": question_for(h, kind, name),
            "acceptedAnswer": {"@type": "Answer", "text": a},
        }
        for h, a in entries(page)
    ]
    if not faqs:
        return None
    doc = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs}
    body = json.dumps(doc, ensure_ascii=False, indent=2)
    return f'{MARK_OPEN}\n<script type="application/ld+json">\n{body}\n</script>\n{MARK_CLOSE}\n'


def strip_previous(page: str) -> str:
    return re.sub(
        re.escape(MARK_OPEN) + r".*?" + re.escape(MARK_CLOSE) + r"\n?",
        "",
        page,
        flags=re.S,
    )


def main() -> int:
    check = "--check" in sys.argv
    pages = sorted(p for p in glob.glob("*/reference/*.html") if not p.endswith("index.html"))
    written = skipped = 0
    total_q = 0

    for path in pages:
        page = open(path, encoding="utf-8").read()
        kind, name = subject_of(path, page)
        if not name:
            print(f"  SKIP  {path}  no h1 to name the subject")
            skipped += 1
            continue

        block = build(page, kind, name)
        if not block:
            print(f"  SKIP  {path}  no entries parsed")
            skipped += 1
            continue

        n = block.count('"@type": "Question"')
        total_q += n

        cleaned = strip_previous(page)
        if "</head>" not in cleaned:
            print(f"  SKIP  {path}  no </head>")
            skipped += 1
            continue
        out = cleaned.replace("</head>", block + "</head>", 1)

        if not check:
            open(path, "w", encoding="utf-8").write(out)
        written += 1
        print(f"  {'would write' if check else 'wrote':11} {path:52} {n:3} q  {kind:9} [{name}]")

    print(f"\n  pages: {written} written, {skipped} skipped, {total_q} questions total")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
